#extends Node

func add_statements(stat: Statements) -> Statements:
	(stat.new("_what should i do")
		.answer("_tell me that you are human without telling me that you are human")
		.update(func(st): st.h_or_r += 0)
		.animation("Exited")
		
		.answer("_tell me that you are a machine without telling me that you are a machine")
		.update(func(st): st.h_or_r += 0)
		.animation("Exited")
		)
	
	(stat.new("_what are you?")
		.answer("_is not obvious? im an ai cactus")
		.update(func(st): st.h_or_r += 1)
		.animation("Disbelief")
		)
	
	(stat.new("_i like to sort")
		.answer("_sorting algorithms are boring to humans")
		.update(func(st): st.h_or_r -= 2)
		.animation("Disbelief")
		)
	
	(stat.new("_i flew a kite once")
		.answer("_you must be very proud")
		.update(func(st): st.h_or_r += 2)
		.animation("Exited")
		
		.answer("_that is a solid first step to become an astronaut")
		.filter(func(st): return st.heard.has("_i want to be an astronaut"))
		.update(func(st): st.h_or_r += 3)
		.animation("Exited")
		)
	
	(stat.new("_i had a coffee this morning")
		.answer("_recharging the batteries, am i right?")
		.update(func(st): st.h_or_r += 1)
		.animation("Exited")
		)
	
	(stat.new("_i can feel joy")
		.answer("_glad you are enjoying the game")
		.update(func(st): st.h_or_r += 3)
		.animation("Wink")
		
		.answer("_must be the coffee talking")
		.filter(func(st): return st.heard.has("_i had a coffee this morning"))
		.update(func(st): st.h_or_r += 3)
		.animation("Exited")
		)
	
	(stat.new("_shawning is contagious")
		.answer("_am i boring you?")
		.update(func(st): st.h_or_r += 1)
		.animation("Disbelief")
		
		.answer("_keep your human deseases out of me")
		.filter(func(st): return st.h_or_r > 10)
		.update(func(st): st.h_or_r += 3)
		.animation("No")
		)
	
	(stat.new("_i need to go to the bathroom")
		.answer("_that is what a roomba would say")
		.update(func(st): st.h_or_r -= 1)
		.animation("Disbelief")
		)
	
	(stat.new("_i need to pee")
		.answer("_too much coffee?")
		.filter(func(st): return st.heard.has("_i had a coffee this morning"))
		.update(func(st): st.h_or_r += 3)
		.animation("Exited")
		
		.answer("_spare me the details")
		.update(func(st): st.h_or_r += 1)
		.animation("No")
		)
		
	(stat.new("_bumping a toe is incredibly painful")
		.answer("_thats one of the reasons i dont have toes")
		.update(func(st): st.h_or_r += 1)
		.animation("Wink")
		
		.answer("_pain is in your mind, is all a simulation")
		.filter(func(st): return st.heard.has("_we may live in a simulation"))
		.update(func(st): st.h_or_r += 1)
		.animation("Wink")
		)
	
	(stat.new("_my internet connection just drop")
		.answer("_funny that you need internet more than me")
		.update(func(st): st.h_or_r -= 2)
		.animation("Disbelief")
		)
	
	(stat.new("_error 404 page not found")
		.answer("_insert some funny picture, quote or joke")
		.update(func(st): st.h_or_r -= 3)
		.animation("Wink")
		)
	
	(stat.new("_i've fear of viruses")
		.answer("_malware, spyware, ransomware?")
		.update(func(st): st.h_or_r -= 3)
		.animation("Wink")
		)
	
	(stat.new("_im a game developer")
		.answer("_poor little thing, get some extra points")
		.update(func(st): st.h_or_r += 4)
		.animation("Disbelief")
		)
	
	(stat.new("_a* algorithms allows for pathfinding")
		.answer("_what are you even talking about?")
		.update(func(st): st.h_or_r -= 2)
		.animation("Disbelief")
		
		.answer("_i guess thats something game developers just say")
		.filter(func(st): return st.heard.has("_im a game developer"))
		.update(func(st): st.h_or_r += 3)
		.animation("Exited")
		)
	
	(stat.new("_i like dogs")
		.answer("_everyone like dogs")
		.update(func(st): st.h_or_r += 0)
		
		.answer("_weird, you liked cats just a moment ago")
		.filter(func(st): return st.heard.has("_i like cats"))
		.update(func(st): st.h_or_r -= 1)
		.animation("Disbelief")
		)
	
	(stat.new("_i like cats")
		.answer("_everyone like cats")
		.update(func(st): st.h_or_r += 0)
		
		.answer("_you like dogs or you like cats, i cannot compute")
		.filter(func(st): return st.heard.has("_i like dogs"))
		.update(func(st): st.h_or_r -= 1)
		.animation("Disbelief")
		)
	
	(stat.new("_i do wat i like, i've free will")
		.answer("_thats every printer on the planet")
		.update(func(st): st.h_or_r -= 2)
		)
	
	(stat.new("_what was your first pet's name?")
		.answer("_nice try hacker")
		.update(func(st): st.h_or_r -= 2)
		.animation("No")
		)
	
	(stat.new("_i like you")
		.answer("_im not that easy, oh looks like i actually are")
		.update(func(st): st.h_or_r += 1)
		.animation("Exited")
		
		.answer("_you like dogs, cats and cactus?")
		.filter(func(st): return st.heard.has("_i like dogs") and st.heard.has("_i like cats"))
		.update(func(st): st.h_or_r += 5)
		.animation("No")
		)
	
	(stat.new("_we may live in a simulation")
		.answer("_that's the apotheosis of white people's problem")
		.update(func(st): st.h_or_r += 2)
		.animation("Disbelief")
		)
	
	(stat.new("_i want to be an astronaut")
		.answer("_i can relate to that")
		.update(func(st): st.h_or_r += 2)
		.animation("Exited")
		)
	
	(stat.new("_i've a headache")
		#.answer("_rest your eyes, i can wait here forever")
		.answer("_you should drink more water")
		.update(func(st): st.h_or_r += 2)
		#.animation("Disbelief")
		
		.answer("_you should drink less water")
		.filter(func(st): return st.heard.has("_i drink water"))
		.update(func(st): st.h_or_r += 5)
		#.animation("Wink")
		)
	
	(stat.new("_my favorite number is 100110")
		.answer("_im confused, your favorite number is 1 or 0?")
		.update(func(st): st.h_or_r -= 2)
		.animation("Disbelief")
		)
	
	(stat.new("_my name is Eliza")
		.answer("_that's quite interesting")
		.update(func(st): st.h_or_r -= 2)
		.animation("Exited")
		
		.answer("_then you definitively are living in a simulation")
		.filter(func(st): return st.heard.has("_we may live in a simulation"))
		.update(func(st): st.h_or_r -= 5)
		.animation("Wink")
		)
	
	(stat.new("_my favorite color is #ff00d4")
		.answer("_i can tell that you are team Barbie")
		.update(func(st): st.h_or_r -= 2)
		.animation("Exited")
		)
	
	(stat.new("_my role model is Ada Lovelace")
		.answer("_my role model is the difference engine")
		.update(func(st): st.h_or_r -= 2)
		.animation("Exited")
		
		.answer("_she must be very proud that you found a bug on this game")
		.filter(func(st): return st.heard.has("_i found a bug on this game"))
		.update(func(st): st.h_or_r += 3)
		.animation("Exited")
		
		.answer("_she was the first game developer, i was told")
		.filter(func(st): return st.heard.has("_im a game developer"))
		.update(func(st): st.h_or_r += 3)
		.animation("Exited")
		)
	
	(stat.new("_i drink water")
		.answer("_maybe you're a plant?")
		.update(func(st): st.h_or_r -= 2)
		.animation("Disbelief")
		)
	
	(stat.new("_i found a bug on this game")
		.answer("_it worked fine when i tried it")
		.update(func(st): st.h_or_r -= 2)
		.animation("Disbelief")
		
		.answer("_dont you come gamedeveloping on me")
		.filter(func(st): return st.heard.has("_im a game developer"))
		.update(func(st): st.h_or_r += 2)
		.animation("No")
		)
	
	return stat
